function toggleSidebar() {
    document.getElementById('sidebar').classList.toggle('active');
    document.querySelector('.sidebar-overlay').classList.toggle('active');
}

document.addEventListener('click', function (e) {
    if (e.target.closest('.nav-link') && window.innerWidth < 992) {
        toggleSidebar();
    }
});

// --- Dynamic Markdown Renderer ---
const contentDiv = document.getElementById('wiki-content');
const links = document.querySelectorAll('.wiki-link');

async function loadMarkdown(fileUrl, activeElement) {
    contentDiv.innerHTML = `<div class="text-center py-5"><div class="spinner-border text-primary" role="status"></div></div>`;
    try {
        const response = await fetch(fileUrl);
        if (!response.ok) throw new Error("Documentation file not found.");
        
        const markdownText = await response.text();
        // Render Markdown to HTML via Marked.js
        contentDiv.innerHTML = marked.parse(markdownText);
        
        // Style tables generated by markdown
        contentDiv.querySelectorAll('table').forEach(tbl => {
            tbl.classList.add('table', 'table-bordered', 'mt-3');
        });
        
        // Clean up old TOCs
        document.querySelectorAll('.toc-sublinks').forEach(el => el.remove());

        // Build new TOC dynamically from h2 elements
        const headings = contentDiv.querySelectorAll('h2');
        if (headings.length > 0 && activeElement) {
            const tocDiv = document.createElement('div');
            tocDiv.className = 'toc-sublinks ps-4 ms-2 mb-2 border-start border-2 border-primary border-opacity-25';
            
            headings.forEach((heading, idx) => {
                // Ensure heading has an ID so we can scroll to it
                if (!heading.id) {
                    heading.id = 'heading-' + idx;
                }

                const a = document.createElement('a');
                a.className = 'nav-link small text-muted py-1';
                a.href = '#' + heading.id;
                // Strip out emojis and extract clean text for the sidebar
                a.innerText = heading.innerText.replace(/[\uD800-\uDBFF][\uDC00-\uDFFF]|\uD83C[\uDF00-\uDFFF]|\uD83D[\uDC00-\uDE4F]/g, '').trim(); 
                
                a.onclick = (ev) => {
                    ev.preventDefault();
                    heading.scrollIntoView({ behavior: 'smooth', block: 'start' });
                };
                tocDiv.appendChild(a);
            });
            
            // Insert the TOC right beneath the active sidebar link
            activeElement.after(tocDiv);
        }

    } catch (err) {
        contentDiv.innerHTML = `<div class="alert alert-danger"><i class="fas fa-exclamation-triangle"></i> Error loading document: ${err.message}</div>`;
    }
}

// Event Listeners for Nav
links.forEach(link => {
    link.addEventListener('click', (e) => {
        e.preventDefault();
        const fileToLoad = e.currentTarget.getAttribute('data-file');
        
        // Highlight active link
        links.forEach(l => l.style.backgroundColor = 'transparent');
        e.currentTarget.style.backgroundColor = 'var(--primary-soft)';
        
        loadMarkdown(fileToLoad, e.currentTarget);
    });
});

// Initial Load
if (links.length > 0) {
    links[0].click(); // Load User Guide by default
}
